### ISSUE TITLE
GeoLite databases no longer publicly available

### ISSUE THREAD

**Issue by fatalglitch** [controlscanmdr/geoip#1]
GeoLite databases are no longer publicly available without creating an account. Need to update documentation and codebase for users to setup and account and provide the API key at startup

https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

https://www.maxmind.com/en/geolite2/signup

**Comment by adonix-dev** [comment]
**Need to update the geoip/Dockerfile**
Because :
(line 16) `ENV GEOIP_BASE_URL      http://geolite.maxmind.com/download/geoip/database`
Is not longer available

**On docker compose:** 
```
Step 8/16 : ADD ${GEOIP_BASE_URL}/${GEOIP_CNTR_DB}.gz /tmp/
ERROR: Service 'geoip' failed to build: ADD failed: Get http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz: dial tcp: lookup geolite.maxmind.com on **your_dns_server** no such host
```

**Comment by fatalglitch** [comment]
Thanks @adonix-dev , I have updated the Dockerfile for GeoIP with the updated location for GeoIP. I had not previously identified an open automated pull source for those files.
